"""create_tables

Revision ID: 001
Revises: 
Create Date: 2022-11-14 17:55:58.561725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension_interaction',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimension_time',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('weekday', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'month', 'year')
    )
    op.create_table('dimension_view',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_video',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=250), nullable=False),
    sa.Column('trending_date', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('publish_time', sa.String(length=36), nullable=False),
    sa.Column('view_group', sa.String(length=36), nullable=False),
    sa.Column('interation_group', sa.String(length=36), nullable=False),
    sa.Column('ratings_disabled', sa.Boolean(), nullable=True),
    sa.Column('video_error_or_removed', sa.Boolean(), nullable=True),
    sa.Column('post_location', sa.String(), nullable=True),
    sa.Column('trending_location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interation_group'], ['dimension_interaction.id'], ),
    sa.ForeignKeyConstraint(['publish_time'], ['dimension_time.id'], ),
    sa.ForeignKeyConstraint(['trending_date'], ['dimension_time.id'], ),
    sa.ForeignKeyConstraint(['view_group'], ['dimension_view.id'], ),
    sa.PrimaryKeyConstraint('id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_video')
    op.drop_table('dimension_view')
    op.drop_table('dimension_time')
    op.drop_table('dimension_interaction')
    # ### end Alembic commands ###
