"""updated_tables

Revision ID: 002
Revises: 001
Create Date: 2022-11-15 03:04:50.572191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id')
    )
    op.add_column('fact_video', sa.Column('category_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'fact_video', 'category', ['category_id'], ['id'])
    op.drop_column('fact_video', 'post_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_video', sa.Column('post_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fact_video', type_='foreignkey')
    op.drop_column('fact_video', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
